run:
  allow-parallel-runners: true
linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 10
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - errname
    - exhaustive
    - exportloopref
    - goconst
    - gocritic
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - noctx
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - golint
        - staticcheck
        - scopelint
        - gochecknoglobals
        - noctx
        - unparam
        - gosec
