apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K3kControlPlane
metadata:
  labels:
    app.kubernetes.io/name: k3kcontrolplane
    app.kubernetes.io/instance: k3kcontrolplane-sample
    app.kubernetes.io/part-of: capi-k3k
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: capi-k3k
  name: k3kcontrolplane-sample
spec:
  # TODO(user): Add fields here
