apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: K3kMachine
metadata:
  labels:
    app.kubernetes.io/name: k3kmachine
    app.kubernetes.io/instance: k3kmachine-sample
    app.kubernetes.io/part-of: capi-k3k
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: capi-k3k
  name: k3kmachine-sample
spec:
  # TODO(user): Add fields here
