name: Release

on:
  push:
    tags:
    - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Release
        env:
          IMG: ghcr.io/enrichman/controller:latest
        run: |
          make docker-build
          make docker-push
